infrastructure:
  - .ci/**/*
  - .github/**/*
  - .binder/**/*
  - Makefile
  - requirements*
  - pyproject.toml
  - dependencies.py
  - setup.*
  - versioneer.py

management:
  - CONTRIBUTING.md
  - LICENSE.txt

