language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

before_install:
 - sudo add-apt-repository -y ppa:pymor/stable
 - sudo apt-get update -q
 - sudo apt-get install -yq python-pymor-demos
 - rm -f $VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/no-global-site-packages.txt
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - pip install python-coveralls pytest-sugar
 - pip install --upgrade markupsafe
 - pip install --upgrade distribute
 - pip install --upgrade numpy
 - pip install --upgrade pytest

# command to install dependencies
install:
 - python setup.py install

# # command to run tests
script: 
 - python setup.py build_ext -i
 - DISPLAY=:99.0 make test

notifications:
  irc: 
    channels:
      - "chat.freenode.net#dune_ms"
    on_success: change
    on_failure: change
  email: 
    on_success: change
    on_failure: change

after_success:
 - coveralls
