language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
 - rm -f $VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/no-global-site-packages.txt
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
# command to install dependencies
install: python ./install.py --recipe travis --virtualenv-dir $VIRTUAL_ENV --without-python-path --python python$TRAVIS_PYTHON_VERSION --only-deps
# # command to run tests
script: tox -e py27
notifications:
  irc: 
    channels:
      - "chat.freenode.net#dune_ms"
    on_success: change
    on_failure: change
  email: 
    on_success: change
    on_failure: change

