language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

before_install:
 - sudo apt-get install -y -qq dolfin-dev python-dolfin fenics ipython python-pyside cython python-opengl
 - git fetch --depth=1000 --tags origin master
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - pip install --upgrade pip
 - pip install python-coveralls 
 - pip install --upgrade markupsafe
 - pip install distribute
 - pip install pyvtk docopt
 - pip install --upgrade pytest
 - pip install --upgrade pytest-cov
 - pip install ipyparallel
 - python -c 'import  dolfin' || echo "import dolfin failed"

# command to install dependencies
install:
 - python setup.py build_ext -i

sudo: required
dist: trusty

cache:
  directories:
    - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

# # command to run tests
script:
        - DISPLAY=:99.0 py.test -k "${PYTEST_MARKER}"

notifications:
  email: 
    on_success: change
    on_failure: change

after_success:
 - coveralls

branches:
  except:
    - gh-pages

env:
  - PYTEST_MARKER="not slow"
  - PYTEST_MARKER="slow"

addons:
  apt:
    packages:
    - debhelper
    - python-pip
    - python-virtualenv
    - python-numpy
    - python-sphinx
    - python-scipy
    - python-matplotlib
    - python-sympy
    - python-dev
    - python3
    - dh-make
    - python-docutils
    - build-essential
    - libblas-dev
    - liblapack-dev
    - libsuitesparse-dev
    - gfortran
    - libqt4-dev
    - gmsh

os:
  - linux
  - osx

matrix:
  allow_failures:
    - os: osx
