jobs:
- job: 'OSX_CI'
  pool:
    vmImage: macOS-10.15
  timeoutInMinutes: 45
  variables:
      PYMOR_HYPOTHESIS_PROFILE: ci
      QT_PREFERRED_BINDING: PyQt5
  strategy:
    maxParallel: 8
    matrix:
      osx_python3.6:
        CONFIG: osx_python3.6
        UPLOAD_PACKAGES: False
      osx_python3.7:
        CONFIG: osx_python3.7
        UPLOAD_PACKAGES: False
      osx_python3.8:
        CONFIG: osx_python3.8
        UPLOAD_PACKAGES: False

  steps:
  - script: |
      brew cask install xquartz
    displayName: install X11

  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - bash: sudo chown -R $USER $CONDA
    displayName: Take ownership of conda installation

  - bash: |
      set -x -e
      conda config --add channels conda-forge
      conda update -y --all
      conda install -y --only-deps pymor
      # these ones are not in the 2020.1 conda build yet
      conda install -y pyevtk mpi4py slycot pytorch pytest-xvfb pyqt
      # these are buildtime, not a runtime,  deps for our conda package
      conda install -y cython pytest-cov pytest
      # install anything which might be a new dependency with pip
      pip install -r requirements.txt
      pip install -r requirements-ci.txt
      pip install -r requirements-optional.txt

    displayName: Configure conda and conda-build

  - script: |
      set -ex
      export PYTHONPATH=${PWD}/src:${PYTHONPATH}
      python setup.py build_ext -i
      python -c "from Qt.QtWidgets import QSizePolicy"
      py.test -sv --junitxml=test_results.xml --cov=src/pymor  \
        --memprof-top-n 50 --memprof-csv-file=memory_usage.txt --cov-context=test \
        --hypothesis-profile ${PYMOR_HYPOTHESIS_PROFILE}
      coverage xml
    displayName: py.test

  - script: |
      bash <(curl -s https://codecov.io/bash)
    displayName: 'Upload to codecov.io'
  - publish: src/pymortests/testdata/check_results/
    artifact: changed_results_$(CONFIG)
    condition: always()
