name: Dependencies changed
on:
  pull_request:
    paths:
      - 'dependencies.py'
      - '.ci/create_conda_env.py'
      - '.ci/gitlab/template.ci.py'

concurrency:
    group: ${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
    cancel-in-progress: true

jobs:
  requirements:
    name: Update dependency files
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r requirements-ci.txt
      - name: Update requirements
        run: python ./dependencies.py
      - name: Upload new requirements
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: requirements
          path: requirements*.txt
  conda:
    name: Update conda environment
    runs-on: ubuntu-22.04
    needs: requirements
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: pyMOR-ci
          miniforge-variant: Mambaforge
          use-mamba: true
          python-version: 3.9
          channels: conda-forge
          channel-priority: true
      - name: Install dependencies
        run: pip install -r requirements-ci.txt
      - uses: actions/download-artifact@v3
        with:
          name: requirements
          path: .
      - name: Update env
        run: python .ci/create_conda_env.py requirements*.txt
      - name: Upload Logfile
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: create_conda_env.log.txt
          path: ./.ci/create_conda_env.log
          if-no-files-found: error
      # The following step seems to overwrite the newly created
      # conda-env.yml
      # - name: Check new env usable
      #   uses: ./.github/actions/miniconda_tests
      #   with:
      #     python: "3.9"
      #     prefix: "/usr/share/miniconda3/envs/pyMOR-ci_changes"
      #     os: "ubuntu-22.04"
      #     results_file: result_requirements.xml
      #     coverage_file: coverage_result_requirements
      #     hypothesis_profile: "dev" # minimal test parametrization
      - name: Upload new requirements
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: conda_env
          path: .ci/conda-env.yml
